apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscription-webapi
  template:
    metadata:
      labels:
        app: subscription-webapi
    spec:
      containers:
        - name: webapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
